### ISSUE TITLE
How to actually play with a bot?

### ISSUE THREAD

**Issue by ccppjava** [jbradberry/ultimate_tictactoe#1]
When following the readme, I got following:
% board-play.py t3 t3.jrb_mcts
usage: board-play.py [-h] [-e EXTRA] {t3} {human} [address] [port]
board-play.py: error: argument player: invalid choice: 't3.jrb_mcts' (choose from 'human')

also, if connect as human, how to actually start the game?
% board-play.py t3 human
You are player #1.
╔═╤═╤═╦═╤═╤═╦═╤═╤═╗
║ │ │ ║ │ │ ║ │ │ ║
╟─┼─┼─╫─┼─┼─╫─┼─┼─╢
║ │ │ ║ │ │ ║ │ │ ║
╟─┼─┼─╫─┼─┼─╫─┼─┼─╢
║ │ │ ║ │ │ ║ │ │ ║
╠═╪═╪═╬═╪═╪═╬═╪═╪═╣
║ │ │ ║ │ │ ║ │ │ ║
╟─┼─┼─╫─┼─┼─╫─┼─┼─╢
║ │ │ ║ │ │ ║ │ │ ║
╟─┼─┼─╫─┼─┼─╫─┼─┼─╢
║ │ │ ║ │ │ ║ │ │ ║
╠═╪═╪═╬═╪═╪═╬═╪═╪═╣
║ │ │ ║ │ │ ║ │ │ ║
╟─┼─┼─╫─┼─┼─╫─┼─┼─╢
║ │ │ ║ │ │ ║ │ │ ║
╟─┼─┼─╫─┼─┼─╫─┼─┼─╢
║ │ │ ║ │ │ ║ │ │ ║
╚═╧═╧═╩═╧═╧═╩═╧═╧═╝
Player: 1

Please enter your action: 1 1
Please enter your action: R 1
Please enter your action: R 2
Please enter your action: R 1 2
Please enter your action: C 1 2
Please enter your action: help
Please enter your action: h
Please enter your action:

**Comment by tamirOK** [comment]
@ccppjava , on each turn you have to pass 4 parameters (indexes): X,Y of global(big) board and x, y of local(small) board.

**Comment by gutouyu** [comment]
@ccppjava you need to use `sudo board-play.py t3 jrb.mcts.uct 127.0.0.1 8888` to start a robot

**Comment by jbradberry** [comment]
Closing due to correct solutions being posted.
